<a href="https://colab.research.google.com/github/Muhammadjon1211/ai_foundation/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [2]:

mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [3]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [4]:
df.tail() # default 5 rows

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [6]:
df.shape()

TypeError: 'tuple' object is not callable

In [7]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [8]:
df.dtypes

cars      object
counts     int64
dtype: object

In [9]:
df.describe(include="all") # numerical columns only

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [10]:
df.iloc[-1]

cars      BMW
counts      3
Name: 6, dtype: object

In [11]:
df.loc[1, "cars"]

'Volvo'

In [12]:
df[df["cars"] == "BMW"]

  cars  counts
0  BMW       3
6  BMW       3

In [13]:
# df.mean(numeric_only=True)

In [14]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [15]:
df.min()

cars      BMW
counts      1
dtype: object

In [16]:
df.max()

cars      Volvo
counts        9
dtype: object

In [17]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [18]:
df.count()

cars      7
counts    7
dtype: int64

In [19]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [20]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None],
}
df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [21]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [22]:
df_missing.dropna()

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [23]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [24]:
df = pd.read_csv("Titanic-Dataset.csv")

df.tail()

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [25]:
df.to_excel("test.xlsx")

In [26]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [27]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']